version: "3.9"

services:
  redis:
    container_name: redis_container
    image: redis
    restart: always
  web:
    restart: always
    build: .
    container_name: web_django_container
    command: bash entrypoint.sh
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: db_postgres_container
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    container_name: nginx_container
    build: ./nginx
    restart: always
    ports:
      - '8084:80'
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
    - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
